// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: riid_ui

#ifndef _RIID_UI_UI_H
#define _RIID_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

//#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image11;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_label5;
extern lv_obj_t * ui_label6;
extern lv_obj_t * ui_label7;
extern lv_obj_t * ui_label4;
extern lv_obj_t * ui_isotope;
extern lv_obj_t * ui_dose;
extern lv_obj_t * ui_cps;
extern lv_obj_t * ui_cpm;
extern lv_obj_t * ui_Navbar;
extern lv_obj_t * ui_stateofcharge;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_chargingico;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen2;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_savedata;
extern lv_obj_t * ui_cleardata;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_lcdbrightnessbar;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_beepvolumebar;
extern lv_obj_t * ui_detvoltagebar;
extern lv_obj_t * ui_detvoltage;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_atom_png);    // assets/atom.png
LV_IMG_DECLARE(ui_img_187700891);    // assets/battery (2).png
LV_IMG_DECLARE(ui_img_lightning_png);    // assets/lightning.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
