// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: riid_ui

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -4);
    lv_obj_set_y(ui_Label13, -106);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Detector Voltage");

    ui_lcdbrightnessbar = lv_bar_create(ui_Screen4);
    lv_bar_set_value(ui_lcdbrightnessbar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_lcdbrightnessbar, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_lcdbrightnessbar, 200);
    lv_obj_set_height(ui_lcdbrightnessbar, 20);
    lv_obj_set_x(ui_lcdbrightnessbar, 0);
    lv_obj_set_y(ui_lcdbrightnessbar, 30);
    lv_obj_set_align(ui_lcdbrightnessbar, LV_ALIGN_CENTER);
    lv_obj_set_style_outline_color(ui_lcdbrightnessbar, lv_color_hex(0x3498DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_lcdbrightnessbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lcdbrightnessbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lcdbrightnessbar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "LCD Brigthness");

    ui_Label15 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 70);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Beep Volume");

    ui_beepvolumebar = lv_bar_create(ui_Screen4);
    lv_bar_set_value(ui_beepvolumebar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_beepvolumebar, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_beepvolumebar, 200);
    lv_obj_set_height(ui_beepvolumebar, 20);
    lv_obj_set_x(ui_beepvolumebar, 0);
    lv_obj_set_y(ui_beepvolumebar, 100);
    lv_obj_set_align(ui_beepvolumebar, LV_ALIGN_CENTER);
    lv_obj_set_style_outline_color(ui_beepvolumebar, lv_color_hex(0x3498DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_beepvolumebar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_beepvolumebar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_beepvolumebar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_detvoltagebar = lv_bar_create(ui_Screen4);
    lv_bar_set_range(ui_detvoltagebar, 20000, 38500);
    lv_bar_set_value(ui_detvoltagebar, 27000, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_detvoltagebar, 275, LV_ANIM_OFF);
    lv_obj_set_width(ui_detvoltagebar, 200);
    lv_obj_set_height(ui_detvoltagebar, 20);
    lv_obj_set_x(ui_detvoltagebar, 0);
    lv_obj_set_y(ui_detvoltagebar, -40);
    lv_obj_set_align(ui_detvoltagebar, LV_ALIGN_CENTER);
    lv_obj_set_style_outline_color(ui_detvoltagebar, lv_color_hex(0x3498DB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_detvoltagebar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_detvoltagebar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_detvoltagebar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_detvoltage = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_detvoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_detvoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_detvoltage, 0);
    lv_obj_set_y(ui_detvoltage, -75);
    lv_obj_set_align(ui_detvoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_detvoltage, "27.5V");
    lv_obj_set_style_text_font(ui_detvoltage, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);


}
