// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: riid_ui

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label5 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label5, -70);
    lv_obj_set_y(ui_label5, -22);
    lv_obj_set_align(ui_label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label5, "Dose:");
    lv_obj_set_style_text_align(ui_label5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label6, -75);
    lv_obj_set_y(ui_label6, 40);
    lv_obj_set_align(ui_label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label6, "CPS:");
    lv_obj_set_style_text_align(ui_label6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label7, -70);
    lv_obj_set_y(ui_label7, 108);
    lv_obj_set_align(ui_label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label7, "CPM:");
    lv_obj_set_style_text_align(ui_label7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label4, -52);
    lv_obj_set_y(ui_label4, -83);
    lv_obj_set_align(ui_label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label4, "Isotope:");
    lv_obj_set_style_text_font(ui_label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_isotope = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_isotope, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_isotope, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_isotope, 70);
    lv_obj_set_y(ui_isotope, -80);
    lv_obj_set_align(ui_isotope, LV_ALIGN_CENTER);
    lv_label_set_text(ui_isotope, "---");
    lv_obj_set_style_text_font(ui_isotope, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dose = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_dose, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dose, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dose, 70);
    lv_obj_set_y(ui_dose, -20);
    lv_obj_set_align(ui_dose, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dose, "---");
    lv_obj_set_style_text_font(ui_dose, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cps = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_cps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cps, 70);
    lv_obj_set_y(ui_cps, 40);
    lv_obj_set_align(ui_cps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cps, "---");
    lv_obj_set_style_text_font(ui_cps, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpm = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_cpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cpm, 70);
    lv_obj_set_y(ui_cpm, 110);
    lv_obj_set_align(ui_cpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpm, "---");
    lv_obj_set_style_text_font(ui_cpm, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Navbar = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Navbar);
    lv_obj_set_width(ui_Navbar, 227);
    lv_obj_set_height(ui_Navbar, 34);
    lv_obj_set_x(ui_Navbar, 0);
    lv_obj_set_y(ui_Navbar, -140);
    lv_obj_set_align(ui_Navbar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Navbar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_stateofcharge = lv_label_create(ui_Navbar);
    lv_obj_set_width(ui_stateofcharge, 25);
    lv_obj_set_height(ui_stateofcharge, 20);
    lv_obj_set_x(ui_stateofcharge, -92);
    lv_obj_set_y(ui_stateofcharge, 2);
    lv_obj_set_align(ui_stateofcharge, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stateofcharge, "100");
    lv_obj_set_style_text_align(ui_stateofcharge, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_stateofcharge, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stateofcharge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Navbar);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 75);
    lv_obj_set_y(ui_time, -1);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "12:10");

    ui_Image3 = lv_img_create(ui_Navbar);
    lv_img_set_src(ui_Image3, &ui_img_187700891);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image3, -87);
    lv_obj_set_y(ui_Image3, 0);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image3, 900);
    lv_img_set_zoom(ui_Image3, 200);

    ui_chargingico = lv_img_create(ui_Navbar);
    lv_img_set_src(ui_chargingico, &ui_img_lightning_png);
    lv_obj_set_width(ui_chargingico, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_chargingico, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_chargingico, -54);
    lv_obj_set_y(ui_chargingico, 0);
    lv_obj_set_align(ui_chargingico, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chargingico, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_chargingico, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_chargingico, 200);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);
    uic_Screen2 = ui_Screen2;

}
